"""empty message

Revision ID: 0adc6393d4a8
Revises: bf6f42b2f99e
Create Date: 2024-08-16 15:08:30.305507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0adc6393d4a8'
down_revision: Union[str, None] = 'bf6f42b2f99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cables', 'type',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cables', 'type',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
