"""empty message

Revision ID: daaf2fd534c2
Revises: 0adc6393d4a8
Create Date: 2024-08-19 15:21:41.899813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daaf2fd534c2'
down_revision: Union[str, None] = '0adc6393d4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cable_mark', 'cables_marks_association', ['cable_id', 'mark_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cable_mark', 'cables_marks_association', type_='unique')
    # ### end Alembic commands ###
