"""empty message

Revision ID: f3cced1428c3
Revises: 
Create Date: 2024-08-13 19:46:00.841758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cced1428c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('descriptions', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('parent', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('documents', sa.String(), nullable=False),
    sa.Column('appointments', sa.String(), nullable=False),
    sa.Column('specifications', sa.String(), nullable=False),
    sa.Column('term_of_use', sa.String(), nullable=False),
    sa.Column('type', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cables_marks_association',
    sa.Column('cable_id', sa.UUID(), nullable=True),
    sa.Column('mark_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ),
    sa.ForeignKeyConstraint(['mark_id'], ['mark.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cables_marks_association')
    op.drop_table('cables')
    op.drop_table('type')
    op.drop_table('news')
    op.drop_table('mark')
    # ### end Alembic commands ###
