version: "3.8"
services:
  cables_app:
    container_name: cables_app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      export MODE=LOCAL &&
      alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - .:/src
    expose:
      - 8001
    ports:
      - "8001:8001"
    networks:
      - practice-network

networks:
  practice-network:
    external: true

